parameters:
  serviceConnection: ""
  subscription: ""
  environment: ""
  resourceGroup: ""
  location: "East US"
  templateFile: ""
  parameterFile: ""

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment ${{ parameters.environment }}'
  inputs:
    azureResourceManagerConnection: ${{ parameters.serviceConnection }}
    subscriptionId: '${{ parameters.subscription }}'
    resourceGroupName: '${{ parameters.resourceGroup }}'
    location: '${{ parameters.location }}'
    csmFile: '${{ parameters.templateFile }}'
    csmParametersFile: '${{ parameters.parameterFile }}'
    deploymentOutputs: 'arm_outputs'
- powershell: |
   echo '$(arm_outputs)'
  displayName: 'PowerShell Script'