trigger: none 

variables:
  azure: ASG
  subscription: "14583dd2-bcc2-45fd-bf9e-48c09c04ae32"
  myPrefix: "iac"
  rg: "$(myPrefix)-arm-templates-$(env)-rg"

stages:
  - stage: arm_ci
    displayName: "ARM Pipeline CI"
    jobs:
      - job: arm_publish
        displayName: "Publish ARM Template"
        steps:
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Pipeline Artifact'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifact: 'arm'
              publishLocation: 'pipeline'
  - stage: arm_dev
    displayName: "ARM Deployment DEV"     
    variables:
      env: "dev"
    jobs:
      - deployment: arm_dev_deployment
        environment: dev
        displayName: "ARM Deployment"
        strategy:
          runOnce:
            deploy:
              steps:
              - template: templates/arm-deployment.yaml
                parameters: 
                  serviceConnection: $(azure)
                  subscription: $(subscription)
                  env: $(env)
                  rg: $(rg)
                  location: "East US"

  - stage: arm_prd
    displayName: "ARM Deployment PRD"  
    variables:
      env: "prd"
    jobs:
      - deployment: arm_prd_deployment
        environment: prd
        displayName: "ARM Deployment"
        strategy:
          runOnce:
            deploy:
              steps:
              - template: templates/arm-deployment.yaml
                parameters: 
                  serviceConnection: $(azure)
                  subscription: $(subscription)
                  env: $(env)
                  rg: $(rg)
                  location: "East US"      